// 旧牛津上海版（一年级起点）全词音标映射：djfml/englishoxfordshanghaiedition anki 牌组提取
// 词表未覆盖的低年级高频词（问候短语等）人工补标准 DJ 音标
// 格式：word -> [IPA, 中文]，用于词汇题题干音标展示与交叉核对
export const IPA_MAP: Record<string, [string, string]> = {
  'a': ['ə', 'two'],
  'about': ['ə\'baut', '关于'],
  'above': ['ə\'bʌv', '在…上方'],
  'accountant': ['ə\'kauntənt', '会计'],
  'actor': ['æktə', '男演员'],
  'actress': ['æktris', '女演员'],
  'aeroplane': ['ɛərəplein', '飞机'],
  'afraid': ['ə\'freid', '害怕的'],
  'after': ['ɑ:ftə', '在…后面'],
  'afternoon': ['ɑ:ftə\'nu:n', '下午；午后'],
  'air': ['εə', '空气；天空；气氛'],
  'all': ['ɔ:l', '全部；都；尽可能的'],
  'am': ['æm', 'are'],
  'ambulance (man)': ['æmbjuləns', '急救员'],
  'america': ['ə\'merikə', '美国；美洲'],
  'american': ['ə\'merikən', '美国的,美国人'],
  'an': ['æn', '一(个)'],
  'and': ['ænd', '和'],
  'angry': ['æŋgri', '生气的'],
  'animal': ['æniməl', '动物'],
  'answer': ['ɑ:nsə', '回答'],
  'answer the phone': ['ɑ:nsə', '接电话'],
  'any': ['eni', '任何'],
  'apple': ['æpl', '苹果'],
  'april': ['eiprəl', '四月'],
  'aquarium': ['ə\'kwɛəriəm', '水族馆；鱼缸'],
  'are': ['ɑ:', '(你)是'],
  'arm': ['ɑ:m', '胳膊'],
  'art and craft': ['krɑ:ft', '工艺美术'],
  'artist': ['ɑ:tist', '画家；艺术家'],
  'ask': ['ɑ:sk', '问；提问'],
  'asleep': ['ə\'sli:p', '睡着的'],
  'at': ['æt', '在… ；在……时'],
  'august': ['ɔ:\'gʌst', '八月'],
  'aunt': ['ɑ:nt', '姑姑；婶；姨'],
  'aviary': ['eiviəri', '鸟巢 禽舍'],
  'awake': ['ə\'weik', '醒着'],
  'away': ['ə\'wei', '离……；外出'],
  'baby': ['beibi', '婴儿；幼畜'],
  'back': ['bæk', '后面'],
  'bag': ['bæɡ', '书包'],
  'bake': ['beik', '烤；烘'],
  'ball': ['bɔːl', '球'],
  'balloon': ['bə\'lu:n', '气球'],
  'banana': ['bə\'nɑ:nə', '香蕉'],
  'bar': ['bɑ:', '栅栏'],
  'basin': ['beisən', '盆；脸盆'],
  'basket': ['bɑ:skit', '筐'],
  'basketball': ['bæskitbɔ:l', '篮球'],
  'bat': ['bæt', '球拍;击球'],
  'bathroom': ['bæθrum', '卫生间；浴室'],
  'be': ['bi:', '是；在'],
  'be quiet': ['kwaiət', '轻点'],
  'beach': ['bi:tʃ', '海滩'],
  'bear': ['bεə', '熊'],
  'because': ['bi\'kɔz', '因为'],
  'become': ['bi\'kʌm', '变成'],
  'bedroom': ['bedrum', '卧室'],
  'begin': ['bi\'gin', '开始'],
  'behind': ['bi\'haind', '在..后面'],
  'bell': ['bel', '铃,铃声'],
  'bench': ['bentʃ', '长凳 法官'],
  'beside': ['bi\'said', '在……旁边'],
  'best': ['best', '最；极'],
  'between': ['bi\'twi:n', '在(两者)之间'],
  'bicycle': ['baɪsɪkl', '自行车'],
  'big': ['biɡ', '大的'],
  'big → bigger': ['big', '更大的'],
  'bigmac': ['mæk', '巨无霸'],
  'bin': ['bin', '垃圾箱；容器'],
  'bird': ['bə:d', '鸟；禽'],
  'birthday': ['bə:θdei', '生日'],
  'black': ['blæk', '黑色的'],
  'blackboard': ['blækbɔ:d', '黑板'],
  'blind': ['blaind', '瞎的'],
  'block': ['blɔk', '大楼；大厦'],
  'blouse': ['blauz', '(女式)衬衫'],
  'blow': ['bləu', '吹'],
  'blue': ['blu:', '蓝色的'],
  'blunt': ['blʌnt', '钝的 头脑迟钝的'],
  'board': ['bɔ:d', '写字板；牌子；伙食'],
  'boat': ['bəut', '船；小船'],
  'body': ['bɔdi', '身体'],
  'bone': ['bəun', '骨头'],
  'book': ['buk', '书'],
  'bookstore': ['bukstɔ:', '书店'],
  'bored': ['bɔ:d', '无聊的；烦人的'],
  'both': ['bəuθ', '两'],
  'bottle': ['bɔtl', '瓶；酒'],
  'box': ['bɔks', '盒子'],
  'boy': ['bɔi', '男孩；儿子；小儿子'],
  'branch': ['brɑ:ntʃ', '树枝'],
  'brave': ['breiv', '勇敢的'],
  'bread': ['bred', '面包'],
  'break': ['breik', '课间休息；休息'],
  'breakfast': ['brekfəst', '早餐'],
  'bright': ['brait', '明亮的；开朗的'],
  'bring': ['briŋ', '带来；拿来'],
  'brother': ['brʌðə', '兄弟'],
  'brown': ['braun', '棕色的'],
  'brush': ['brʌʃ', '刷(子)'],
  'bus': ['bʌs', '公共汽车'],
  'bus driver': ['draivə', '司机'],
  'bus stop': ['stɔp', '公共汽车站'],
  'busy': ['bizi', '忙'],
  'but': ['bʌt', '但是；而是；然而'],
  'butter': ['bʌtə', '黄油；奶油'],
  'buy': ['bai', '买'],
  'by (bus car)': ['bai', '表示方法通过'],
  'cabbage': ['kæbidʒ', '卷心菜'],
  'cage': ['keidʒ', '笼子；监牢'],
  'cake': ['keik', '蛋糕'],
  'call': ['kɔ:l', '叫'],
  'can': ['kæn', '能够；可以；究竟'],
  'can\'t': ['kɑ:nt', '不能'],
  'cannot': ['kænɔt', '不能'],
  'cap': ['kæp', '帽子'],
  'capital': ['kæpitəl', '首都'],
  'car': ['kɑ:', '小汽车'],
  'carrot': ['kærət', '胡萝卜；红头发'],
  'castle': ['kɑ:sl', '城堡'],
  'cat': ['kæt', '猫；猫科动物'],
  'catc(bus)': ['kætʃ', '赶上；抓住'],
  'catch butterfly': ['kætʃ', '捉蝴蝶'],
  'caterpillar': ['kætə,pilə', '毛虫；蝶'],
  'chair': ['tʃɛə', '椅子'],
  'chase': ['tʃeis', '追赶'],
  'cheap': ['tʃi:p', '便宜的；廉价的'],
  'chess': ['tʃes', '西洋棋'],
  'chicken': ['tʃikin', '鸡肉'],
  'child': ['tʃaild', '小孩'],
  'children': ['tʃildrən', '小孩(复数)'],
  'china': ['tʃaɪnə', '中国'],
  'chinese': ['tʃai\'ni:z', '中国的；汉语；中国人'],
  'chocolate': ['tʃɔkəlit', '巧克力'],
  'chopsticks': ['tʃɔpstik', '筷子（复数）'],
  'cinema': ['sinəmə', '电影院'],
  'class': ['klɑ:s', '班'],
  'classmate': ['klɑ:smeit', '同学'],
  'classroom': ['klɑ:srum', '教室'],
  'clean': ['kli:n', '清洁的'],
  'clean the room': ['kli:n', '打扫房间'],
  'clean → cleaned': ['kli:n', '打扫'],
  'cleaner': ['kli:nə', '清洁工'],
  'climb': ['klaim', '往上爬'],
  'climb mountains': ['klaim', '爬山'],
  'clock': ['klɔk', '钟'],
  'close': ['kləuz', '关；结账'],
  'close the window': ['kləʊz ðə wɪndəʊ', '关窗'],
  'cloud': ['klaud', '云'],
  'cloudy': ['klaudi', '多云的；阴天的'],
  'coat': ['kəut', '上衣'],
  'cocoon': ['kə\'ku:n', '茧；卵袋'],
  'coffee': ['kɔfi', '咖啡'],
  'coke': ['kəuk', '可乐'],
  'cold': ['kəuld', '寒冷的'],
  'collect leaves': ['kə\'lekt', '收集树叶'],
  'collect stamps→collecting stamps': ['kə\'lekt', '集邮'],
  'colour': ['kʌlə', '给……颜色'],
  'come from': ['kʌm', '来自'],
  'come in': ['kʌm ɪn', '进来'],
  'come in.': ['kʌm in', '进来'],
  'comic': ['kɔmik', '连环图画；喜剧的'],
  'comic book': ['kɔmik', '漫画'],
  'computer': ['kəm\'pju:tə', '计算机'],
  'content': ['kən\'tent', '（书刊等的）目录；内容'],
  'cook': ['kuk', '厨师'],
  'cook dinner': ['kuk', '做饭'],
  'cool': ['ku:l', '凉爽的'],
  'corm': ['kɔ:m', '谷物'],
  'count': ['kaunt', '数'],
  'count insects': ['kauʊnt', '数昆虫'],
  'country park': ['kʌntri', '乡村公园'],
  'cousin': ['kʌzn', '堂（表）兄弟姐妹'],
  'crayon': ['kreiən', '蜡笔'],
  'crisp': ['krisp', '松脆饼干；松脆之物'],
  'crocodile': ['krɔkədail', '鳄鱼'],
  'cross': ['krɔ:s', '穿过 度过'],
  'crossing': ['krɔ:siŋ', '十字路口'],
  'cup': ['kʌp', '杯子；奖杯'],
  'cupboard': ['kʌbəd', '小厨；碗柜'],
  'cushion': ['kuʃən', '靠垫；坐垫'],
  'dad': ['dæd', '爸爸'],
  'daily': ['deili', '每日的；日常的'],
  'dance': ['dɑ:ns', '跳舞；舞蹈'],
  'dangerous': ['deindʒərəs', '危险的'],
  'dark': ['dɑ:k', '黑暗'],
  'date': ['deit', '日期'],
  'daughter': ['dɔ:tə', '女儿；媳妇；妇女'],
  'day': ['dei', '白天；时代；……节日'],
  'dear': ['diə', '亲爱的；可爱的'],
  'december': ['di\'sembə', '十二月'],
  'dentist': ['dentist', '牙医'],
  'desk': ['desk', '课桌'],
  'dessert': ['di\'zə:t', '甜点；餐后甜点'],
  'diary': ['daiəri', '日记；日记簿'],
  'dictionary': ['dikʃəneri', '字典'],
  'different': ['difərənt', '不同的'],
  'dig': ['dig', '挖'],
  'dining': ['dainiŋ', '进餐'],
  'dinosaur': ['dainəsɔ:', '恐龙'],
  'dirty': ['də:ti', '脏的'],
  'dish': ['diʃ', '碟子；盘子'],
  'diver': ['daivə', '跳水者；潜水员'],
  'dive→diving': ['daiv', '跳水'],
  'do': ['du:', '做'],
  'do an experiment': ['du:', '做实验'],
  'do morning exercises': ['mɔ:niŋ', '晨练'],
  'doctor': ['dɔktə', '医生；博士'],
  'doesn’t=does not': ['dʌz', 'does not的缩略形式'],
  'dog': ['dɔg', '狗'],
  'doll': ['dɔl', '玩具娃娃'],
  'dolphin': ['dɔlfin', '海豚'],
  'donkey': ['dɔŋki', '驴；傻瓜'],
  'door': ['dɔ:', '门；出口'],
  'down': ['daun', '向下'],
  'draw': ['drɔ:', '画'],
  'draw pictures': ['drɔ:', '画画'],
  'dress': ['dres', '连衣裙'],
  'drill': ['dril', '钻头 钻床'],
  'drink': ['driŋk', '饮料'],
  'drink water': ['driŋk', '喝水'],
  'drum': ['drʌm', '鼓'],
  'dry': ['drai', '干的 干旱的'],
  'duck': ['dʌk', '鸭子'],
  'duckling': ['dʌkliŋ', '小鸭'],
  'durian': ['djuəriən', '榴莲'],
  'each': ['i:tʃ', '每个各自的'],
  'each other': ['ʌðə', '互相'],
  'ear': ['iə', '耳朵'],
  'early': ['ə:li', '早,早的'],
  'eat': ['i:t', '吃'],
  'eat breakfast': ['i:t', '吃早饭'],
  'egg': ['eɡ', '蛋'],
  'eight': ['eit', '八'],
  'eighteen': ['ei\'ti:n', '十八'],
  'eighth': ['eitθ', '第八'],
  'eighty': ['eiti', '八十'],
  'elephant': ['elifənt', '大象'],
  'eleven': ['i\'levən', '十一'],
  'eleventh': ['i\'levnθ', '第十一'],
  'elf': ['elf', '小精灵；顽皮的孩子'],
  'empty': ['empti', '空的'],
  'engine': ['endʒin', '引擎；发动机'],
  'engineer': [',endʒi\'niə', '工程师'],
  'england': ['inglənd', '英国'],
  'english': ['iŋgliʃ', '英国的；英语；英国人'],
  'eraser': ['i\'reizə', '橡皮'],
  'evening': ['i:vniŋ', '傍晚；晚上'],
  'every': ['evri', '每个的'],
  'everywhere': ['evrihwɛə', '到处；彻底'],
  'excited': ['ik\'saitid', '兴奋的'],
  'excuse me.': ['iks\'kju:z', '对不起！请原谅！'],
  'exercise': ['eksəsaiz', '练习；运动'],
  'expression': ['iks\'preʃən', '表达；表现力；表情'],
  'eye': ['ai', '眼睛'],
  'face': ['feis', '脸'],
  'factory': ['fæktəri', '工厂'],
  'fall': ['fɔ:l', '秋天'],
  'family': ['fæmili', '家；家庭；家族'],
  'fan': ['fæn', '扇子；电扇；螺旋桨'],
  'far': ['fɑ:', '远'],
  'farm': ['fɑ:m', '农场'],
  'farmer': ['fɑ:mə', '农民'],
  'fast': ['fɑ:st', '快'],
  'fat': ['fæt', '胖的；厚的；大量的'],
  'father': ['fɑːðə', '父亲'],
  'favorite': ['feivərit', '特别喜爱'],
  'february': ['februəri', '二月'],
  'feed': ['fi:d', '喂养；饲养'],
  'feeler': ['fi:lə', '触角；触须'],
  'felt pen': ['felt', '毡头笔'],
  'fifteen': ['fɪftiːn', '十五'],
  'fifteenth': ['fif\'ti:nθ', '十五'],
  'fifth': ['fifθ', '第五'],
  'fifty': ['fifti', '五十'],
  'fight': ['fait', '打架'],
  'finger': ['fiŋɡə', '手指'],
  'fire': ['faiə', '火'],
  'fireman': ['faiəmən', '消防员'],
  'first': ['fə:st', '第一；首先'],
  'fish': ['fiʃ', '鱼'],
  'five': ['faiv', '五'],
  'floor': ['flɔ:', '地板'],
  'flour': ['flauə', '面粉；粉状物质'],
  'flower': ['flauə', '花；开花；精华'],
  'fluffy': ['flʌfi', '蓬松的'],
  'fly': ['flai', '飞'],
  'fly kites': ['flai', '放风筝'],
  'food': ['fu:d', '食物'],
  'foot': ['fut', '脚'],
  'football': ['futbɔ:l', '足球；橄榄球'],
  'for': ['fɔ:', '为；代替；因为；为得到'],
  'fork': ['fɔ:k', '叉子；岔口'],
  'forty': ['fɔ:ti', '四十'],
  'fountain': ['fauntin', '喷水池；泉水'],
  'four': ['fɔ:', '四'],
  'fourteen': ['fɔ:\'ti:n', '十四'],
  'fourth': ['fɔ:θ', '第四；四分之一'],
  'fox': ['fɔks', '狐狸；狡猾的人'],
  'french fries': ['frentʃ', '炸薯条'],
  'friday': ['fraidi', '星期五'],
  'fridge': ['fridʒ', '冰箱'],
  'friend': ['frend', '朋友'],
  'frog': ['frɔg', '青蛙'],
  'from': ['frɔm', '从……'],
  'front': ['frʌnt', '前面；前部；正面'],
  'fruit': ['fru:t', '水果；果实'],
  'full': ['ful', '饱的；充满的'],
  'fun': ['fʌn', '乐趣；娱乐'],
  'furniture': ['fə:nitʃə', '家具'],
  'game': ['ɡeim', '游戏'],
  'garden': ['gɑ:dn', '花园；菜园；游乐场'],
  'geese': ['ɡi:s', '鹅(复数)'],
  'get': ['ɡet', '得到'],
  'get to': ['get', '到达'],
  'get → got': ['get', '到达'],
  'giant': ['dʒaiənt', '巨人；伟人'],
  'giraffe': ['dʒi\'rɑ:f', '长颈鹿'],
  'girl': ['ɡə:l', '女孩；女儿'],
  'give': ['ɡiv', '给；生产；出售'],
  'glass': ['ɡlɑ:s', '玻璃杯'],
  'glasses': ['glɑ:siz', '眼镜；双筒望远镜'],
  'glove': ['glʌv', '手套'],
  'glue': ['glu:', '胶水'],
  'go': ['ɡəu', '去'],
  'go fishing → went fishing': ['fiʃiŋ', '去钓鱼'],
  'go hiking': ['haikiŋ', '去远足'],
  'go hiking → went hiking': ['haikiŋ', '去郊游'],
  'go ice-skating → went ice-skating': ['ais', '去滑冰'],
  'go out': ['gəu aut', '出去；外出'],
  'go shopping': ['gəu', '购物'],
  'go skiing → went skiing': ['ski:iŋ', '去滑雪'],
  'go swimming→went swimmin': ['swimiŋ', '去游泳'],
  'go to a park → went to a park': ['pɑ:k', '去公园'],
  'go → went': ['gəu', '去'],
  'goal': ['gəul', '得分；守门员'],
  'good': ['ɡud', '好的'],
  'good afternoon': ['ɡʊd ɑːftənuːn', '下午好'],
  'good evening': ['ɡʊd iːvnɪŋ', '晚上好'],
  'good idea': ['ai\'diə', '好主意'],
  'good job': ['dʒɔb', '干的好'],
  'good morning': ['ɡʊd mɔːnɪŋ', '早上好'],
  'goodbye': ['ɡʊdbaɪ', '再见'],
  'goose': ['ɡu:s', '鹅'],
  'got': ['gɔt', '(动词get的过去式)'],
  'go→goes': ['gəʊz', '去'],
  'grammar': ['græmə', '语法'],
  'grandma': ['grændmɑ:', '奶奶；外婆'],
  'grandpa': ['grændpɑ:', '爷爷；外公'],
  'grape': ['greip', '葡萄；葡萄酒'],
  'grass': ['grɑ:s', '草；草坪'],
  'green': ['ɡri:n', '绿色的'],
  'grey': ['grei', '灰色'],
  'ground': ['graʊnd', '地面'],
  'group': ['gru:p', '组；小组'],
  'guess': ['ɡes', '猜'],
  'guitar': ['gi\'tɑ:', '吉他'],
  'hair': ['heə', '头发'],
  'half': ['hɑ:f', '半'],
  'half past …': ['hɑ:f', '点半'],
  'hamburger': ['hæmbə:ɡə', '汉堡包'],
  'hammer': ['hæmə', '锤子；链球'],
  'hand': ['hænd', '手'],
  'happy': ['hæpi', '高兴的'],
  'hare': ['hєə', '野兔'],
  'hat': ['hæt', '帽子'],
  'have': ['hæv', '有'],
  'have a cold': ['kəuld', '感冒'],
  'have a fever': ['hæv', '发烧'],
  'have a headache': ['hedeik', '头疼'],
  'have a picnic': ['piknik', '举行野餐'],
  'have a sore throat': ['sɔ:', '喉咙疼'],
  'have a toothache': ['tu:θeik', '牙疼'],
  'have english class': ['hæv', '上英语课'],
  'hay': ['hei', '干草'],
  'head': ['hed', '头'],
  'hear': ['hiə', '听；听见'],
  'heavy': ['hevi', '重的；沉重的'],
  'heavy → heavier': ['hi:vi', '更重的'],
  'hello': ['hələʊ', '你好'],
  'help': ['help', '帮助；治疗'],
  'her': ['hə:', '她(宾格)'],
  'here': ['hiə', '这儿'],
  'here you are': ['hɪə juː ɑː', '给你'],
  'hers': ['hə:z', '她的'],
  'hey': ['hei', '嗨'],
  'hi': ['haɪ', '嗨'],
  'hide': ['haid', '把……藏起来'],
  'high': ['hai', '高的'],
  'hiking': ['haikiŋ', '徒步旅行'],
  'him': ['him', '他(宾格)'],
  'his': ['hiz', '他的'],
  'his evening': ['ðis', '今天晚上'],
  'hissing': ['hisiŋ', '发出嘶嘶声'],
  'hobby': ['hɔbi', '爱好'],
  'hole': ['həul', '洞；孔眼'],
  'home': ['həum', '家'],
  'homework': ['həumwə:k', '家庭作业'],
  'honey': ['hʌni', '蜂蜜'],
  'hoop': ['hu:p', '呼啦圈；戒指；篮圈'],
  'hooray': ['hu\'rei', '好啊（感叹词）'],
  'hop': ['hɒp', '单脚跳'],
  'horse': ['hɔ:s', '马'],
  'hot': ['hɒt', 'cold'],
  'hot dog': ['hɒt dɒɡ', '热狗'],
  'house': ['haus', '房子'],
  'how': ['hau', '怎么；如何'],
  'how many': ['haʊ meni', '多少（数量）'],
  'how much': ['haʊ mʌtʃ', '多少钱'],
  'humming': ['hʌmiŋ', '发出嗡嗡声'],
  'hundred': ['hʌndrəd', '一百'],
  'hungry': ['hʌŋgri', '饥饿的'],
  'hurry': ['hʌri', '匆忙；赶紧'],
  'hurry up': ['hʌri ʌp', '快点'],
  'hurt': ['hə:t', '疼痛'],
  'i  am': ['æm', '(我)是'],
  'if': ['if', '如果'],
  'in': ['ɪn', 'on'],
  'ink': ['iŋk', '墨水'],
  'insect': ['insekt', '昆虫'],
  'instrument': ['instrumənt', '器具；仪器'],
  'invitation': [',invi\'teiʃən', '请帖'],
  'is': ['ɪz', 'am'],
  'island': ['ailənd', '岛；安全岛'],
  'it': ['it', '它'],
  'jacket': ['dʒækit', '外衣；夹克；皮'],
  'january': ['dʒænjueri', '一月'],
  'jean': ['dʒi:n', '牛仔裤；斜纹棉布'],
  'join': ['dʒɔin', '参加'],
  'juice': ['dʒu:s', '果汁；汁'],
  'july': ['dʒu:\'lai', '七月'],
  'jump': ['dʒʌmp', '跳'],
  'june': ['dʒu:n', '六月'],
  'jungle': ['dʒʌŋgl', '丛林'],
  'kangaroo': [',kæŋgə\'ru:', '袋鼠'],
  'key': ['ki:', '钥匙'],
  'kitchen': ['kitʃin', '厨房'],
  'kite': ['kaɪt', '风筝'],
  'knee': ['ni:', '膝盖；膝部'],
  'knife': ['naif', '小刀；手术刀；匕首'],
  'lady': ['leidi', '女士；夫人；小姐'],
  'lake': ['leik', '湖'],
  'large': ['lɑ:dʒ', '大的；宽大的'],
  'last': ['lɑ:st', '上一个的；仅余的；留在最后的'],
  'lay（eggs）': ['lei', '下（蛋）；产卵'],
  'learn chinese → learned chinese': ['lə:n', '学汉语'],
  'leave': ['li:v', '离开'],
  'left': ['left', '左边'],
  'leg': ['leɡ', '腿'],
  'lesson': ['lesən', '功课；课程；教训'],
  'let': ['let', '让；出租'],
  'letter': ['letə', '信'],
  'library': ['laibrəri', '图书馆'],
  'life': ['laif', '生命；生活'],
  'light': ['lait', '灯；光；火花；眼神'],
  'like': ['laik', '爱好'],
  'lime': ['laim', '酸橙；菩提树'],
  'lion': ['laiən', '狮子；勇敢的人'],
  'listen': ['lisən', '听'],
  'listen to music': ['lisn', '听音乐'],
  'little': ['litl', '少许；一点点；幼小'],
  'live': ['liv', '居住；生活'],
  'live→lives': ['liv', '居住'],
  'lizard': ['lizəd', '蜥蜴'],
  'log': ['lɔg', '原木；木材'],
  'long': ['lɔŋ', '长的'],
  'long hair': ['hεə', '长头发'],
  'long → longer': ['lɔŋ', '更长的'],
  'look at the blackboard': ['lʊk æt ðə blækbɔːd', '看黑板'],
  'lorry': ['lɔ:ri', '卡车'],
  'loud': ['laud', '响的'],
  'love': ['lʌv', '爱'],
  'lunch': ['lʌntʃ', '午餐'],
  'make': ['meik', '做；制作；作出举动'],
  'make a snowman': ['snəʊmæn', '堆雪人'],
  'make kites→making kites': ['meik', '制作风筝'],
  'man': ['mæn', '男子'],
  'many': ['meni', 'old'],
  'map': ['mæp', '地图'],
  'march': ['mɑ:tʃ', '三月'],
  'mask': ['mɑ:sk', '面具；遮蔽物；口罩'],
  'match': ['mætʃ', '比赛；对手'],
  'maths': ['mæθs', '数学'],
  'matter': ['mætə', '事情；麻烦'],
  'may': ['mei', '可以'],
  'maybe': ['meibi', '也许；可能'],
  'me': ['mi:', '我(宾格)'],
  'mean': ['mi:n', '意指'],
  'member': ['membə', '成员'],
  'mice': ['mais', '老鼠（复数）'],
  'milk': ['milk', '牛奶'],
  'millimeter': ['mili,mi:tə', '毫米；公厘'],
  'mine': ['main', '我的'],
  'minus': ['mainəs', '减'],
  'mirror': ['mirə', '镜子；榜样'],
  'miss': ['mis', '女士；小姐；少女'],
  'model': ['mɔdl', '模型；模特；模范'],
  'module': ['mɔdju:l', '单元；组件'],
  'monday': ['mʌndi', '星期一'],
  'money': ['mʌni', '钱；收入'],
  'monkey': ['mʌŋki', '猴子；顽童'],
  'month': ['mʌnθ', '月'],
  'moon': ['mu:n', '月亮；月光'],
  'mop': ['mɔp', '擦；抹；拖'],
  'morning': ['mɔ:niŋ', '早晨；上午'],
  'moth': ['mɔθ', '蛾；蛀虫'],
  'mother': ['mʌðə', '母亲'],
  'motherland': ['mʌðəlænd', '祖国'],
  'motorbike': ['məutəbaik', '摩托车'],
  'mountain': ['mauntin', '山；山脉'],
  'mouse': ['maus', '老鼠'],
  'mouth': ['mauθ', '嘴'],
  'mr.': ['mistə', '先生(mister的缩写)'],
  'much': ['mʌtʃ', '许多；很；非常'],
  'mum': ['mʌm', '妈妈（口语）'],
  'music': ['mju:zik', '音乐'],
  'musical': ['mju:zikəl', '音乐的'],
  'must': ['mʌst', '必须；应该'],
  'name': ['neim', '名字'],
  'national': ['næʃənəl', '国家的'],
  'national flag': ['flæɡ', '国旗'],
  'near': ['niə', '靠近'],
  'need': ['ni:d', '需要'],
  'nest': ['nest', '鸟巢'],
  'new': ['nju:', '新的；新闻'],
  'news': ['nju:z', '消息；新闻'],
  'newspaper': ['nju:s,peipə', '报纸'],
  'next to': ['nekst', '与……相邻'],
  'next week': ['wi:k', '下周'],
  'night': ['nait', '夜间；黑暗'],
  'nine': ['nain', '九'],
  'nineteen': [',nain\'ti:n', '十九'],
  'ninety': ['nainti', '九十'],
  'ninth': ['nainθ', '第九；九分之一'],
  'no': ['nəu', '不；不是'],
  'nod': ['nɔd', '点头'],
  'noise': ['nɔiz', '噪声'],
  'noodle(s)': ['nu:dl', '面条（通常复数）'],
  'noon': ['nu:n', '中午'],
  'nose': ['nəuz', '鼻子'],
  'not': ['nɔt', '不；不是的'],
  'note': ['nəut', '纸币；笔记'],
  'november': ['nəu\'vembə', '十一月'],
  'now': ['nau', '现在'],
  'number': ['nʌmbə', '号；号码'],
  'nurse': ['nə:s', '护士'],
  'o\'clock': ['ə\' klɔk', '点钟'],
  'ocean': ['əuʃən', '海洋'],
  'october': ['ɔk\'təubə', '十月'],
  'of course': ['kɔ:s', '当然'],
  'often': ['ɔ:fən', '经常；常常'],
  'oh no': ['əu', '噢；不'],
  'old': ['əuld', '年老的'],
  'old → older': ['əuld', '年龄更大的'],
  'once': ['wʌns', '一次'],
  'one': ['wʌn', '一'],
  'only': ['əunli', '只有；仅仅'],
  'open': ['əupən', '开；开阔的'],
  'open the door': ['əʊpən ðə dɔː', '开门'],
  'or': ['ɔ:', '或；还是'],
  'oral': ['ɔ:rəl', '口试'],
  'orange': ['ɔ:rindʒ', '橙色的 桔子'],
  'other': ['ʌðə', '另外的'],
  'our': ['auə', '我们的'],
  'ours': ['auəz', '我们的'],
  'out': ['aut', '出；在外'],
  'outside': ['aut\'said', '向外面；在外面'],
  'over': ['əuvə', '越(过)'],
  'owl': ['aul', '猫头鹰'],
  'packet': ['pækit', '小包'],
  'page': ['peidʒ', '页'],
  'paint': ['peint', '颜料'],
  'painting': ['peintiŋ', '绘画；上油漆'],
  'pair': ['pєə', '一双'],
  'palace': ['pælis', '宫殿'],
  'panda': ['pændə', '熊猫'],
  'pant': ['pænt', '长裤'],
  'paper': ['peipə', '纸；报纸；报告'],
  'parcel': ['pɑ:sl', '小包；包裹'],
  'parents': ['pєərənts', '父母'],
  'park': ['pɑ:k', '公园'],
  'parrot': ['pærət', '鹦鹉'],
  'party': ['pɑ:ti', '聚会；党派'],
  'pass': ['pɑ:s', '传递；经过；度过'],
  'past': ['pɑ:st', '过'],
  'pear': ['pεə', '梨'],
  'peasant': ['pezənt', '农民'],
  'peel': ['pi:l', '剥（皮）'],
  'pen': ['pen', '钢笔'],
  'pencil': ['pensəl', '铅笔'],
  'pencil-case': ['penslkeis', '铅笔盒'],
  'people': ['pi:pl', '人；人民；民族'],
  'pet': ['pet', '宠物；宝贝'],
  'photo': ['fəutəu', '照片'],
  'physical education': ['fizikəl', '体育课'],
  'piano': ['pi\'ænəu', '钢琴'],
  'pick': ['pik', '采；摘'],
  'pick up leaves': ['pik', '采摘树叶'],
  'picnic': ['piknik', '野餐'],
  'picture': ['piktʃə', '图画；照片'],
  'piece': ['pi:s', '片'],
  'pig': ['piɡ', '猪'],
  'pilot': ['pailət', '飞行员；舵手'],
  'pineapple': ['pain,æpl', '菠萝；凤梨'],
  'pingpong': ['piŋpɔŋ', '乒乓球；桌球'],
  'pink': ['piŋk', '粉色的'],
  'pioneer': [',paiə\'niə', '先锋'],
  'place': ['pleis', '地方；住所；席位'],
  'plane': ['plein', '飞机'],
  'plant': ['plɑ:nt', '种植'],
  'plant trees': ['plɑ:nt', '种树'],
  'plate': ['pleit', '盘子'],
  'play': ['plei', '玩；演奏；表演'],
  'play chess': ['plei', '下棋'],
  'play sports': ['plei', '进行体育运动'],
  'play the piano': ['plei', '弹钢琴'],
  'play the violin→playing the violin': ['pleiiŋ', '拉小提琴'],
  'play → played': ['plei', '玩'],
  'playground': ['pleiɡraund', '操场'],
  'please': ['pli:z', '请'],
  'plum': ['plʌm', '梅子；洋李'],
  'poem': ['pəuim', '（一首）诗'],
  'policeman': ['pə\'li:smən', '男警察'],
  'policewoman': ['pə\'li:s,wumən', '女警'],
  'pond': ['pɔnd', '水池；池塘'],
  'pool': ['pu:l', '池'],
  'pop': ['pɔp', '流行；流行音乐'],
  'post card': ['pəust', '明信片'],
  'postman': ['pəustmən', '邮递员'],
  'potato': ['pə\'teitəu', '马铃薯'],
  'project': ['prə\'dʒekt', '方案；计划'],
  'puppet': ['pʌpit', '木偶；傀儡'],
  'puppy': ['pʌpi', '小狗'],
  'purple': ['pə:pl', '紫色的'],
  'puzzle': ['pʌzl', '拼图板；猜谜'],
  'quarter': ['kwɔ:tə', '四分之一；一刻'],
  'question': ['kwestʃən', '问题'],
  'quiet': ['kwaiət', '安静的'],
  'rabbit': ['ræbit', '兔子'],
  'race': ['reis', '比赛'],
  'radio': ['reidiəu', '收音机；电台'],
  'rain': ['rein', '雨；下雨'],
  'rainbow': ['reinbəu', '彩虹'],
  'raindrop': ['reindrɔp', '雨点'],
  'rainy': ['reini', '雨天；多雨的'],
  'read': ['ri:d', '读；察觉'],
  'read a book': ['rid', '看书'],
  'ready': ['redi', '准备好了'],
  'read→reads': ['rid', '读；看'],
  'recorder': ['ri\'kɔ:də', '八孔直笛'],
  'rectangle': ['rek\'tæŋgl', '长方形'],
  'red': ['red', '红色的'],
  'rest': ['rest', '休息'],
  'restaurant': ['restərɔnt', '餐厅'],
  'rice': ['rais', '米饭'],
  'ride': ['raid', '骑；乘'],
  'ride a bike→riding a bike': ['raid', '骑自行车'],
  'right': ['rait', '对的'],
  'rise': ['raiz', '升起'],
  'river': ['rivə', '河流；巨量'],
  'road': ['rəud', '路；街道'],
  'robot': ['rɔbət', '机器人'],
  'rock': ['rɔk', '石头；磐石'],
  'roll': ['rəul', '打滚；转动；晃动'],
  'roll over': ['rəul', '打滚'],
  'roof': ['ru:f', '屋顶；车顶'],
  'room': ['ru:m', '房间'],
  'rope': ['rəup', '绳子'],
  'rough': ['rʌf', '粗糙的；毛茸茸的'],
  'round': ['raund', '圆的'],
  'row': ['rau', '划；划船'],
  'row a boat → rowed a boat': ['rau', '划船'],
  'rubbish': ['rʌbiʃ', '垃圾；废话'],
  'rug': ['rʌg', '小地毯'],
  'rule': ['ru:l', '规则'],
  'ruler': ['ru:lə', '尺子'],
  'run': ['rʌn', '跑；行驶；运行；逃跑'],
  'russian': ['rʌʃən', '俄语,俄国人'],
  'sad': ['sæd', '忧伤的；悲伤的'],
  'sail': ['seil', '驾驶（船只）'],
  'sale': ['seil', '打折销售；出售'],
  'salesperson': ['seilz,pə:sən', '销售员'],
  'salt': ['sɔ:lt', '盐；风趣'],
  'same': ['seim', '相同的'],
  'saturday': ['sætədi', '星期六'],
  'sausage': ['sɔ:sidʒ', '香肠'],
  'say': ['sei', '说'],
  'scarf': ['skɑ:f', '领巾'],
  'school': ['sku:l', '学校'],
  'science': ['saiəns', '科学；技术'],
  'scissors': ['sizəz', '剪刀'],
  'score': ['skɔ:', '得分；起跑线；终点线'],
  'screwdriver': ['skru:,draivə', '螺丝刀'],
  'seal': ['si:l', '海豹'],
  'season': ['si:zn', '季节'],
  'seat': ['si:t', '座位'],
  'second': ['sekənd', '第二'],
  'see': ['si:', '看见'],
  'see elephant → saw elephant': ['si:', '看大象（'],
  'seed': ['si:d', '种子'],
  'self': ['self', '自己；自我；本质'],
  'september': ['sep\'tembə', '九月'],
  'seven': ['sevən', '七'],
  'seventeen': [',sevn\'ti:n', '十七'],
  'seventh': ['sevnθ', '第七'],
  'seventy': ['sevnti', '七十'],
  'shadow': ['ʃædəu', '影子；幻象；阴影'],
  'shake': ['ʃeik', '摇；抖动'],
  'shaker': ['ʃeikə', '摇动器；搅拌器'],
  'shark': ['ʃɑ:k', '鲨鱼'],
  'sharp': ['ʃɑ:p', '尖的；锋利的'],
  'sharpener': ['ʃɑ:pənə', '卷笔刀'],
  'sheep': ['ʃi:p', '羊；害羞的人；蠢人'],
  'sheet': ['ʃi:t', '印刷品；表格'],
  'shelf': ['ʃelf', '书架'],
  'shell': ['ʃel', '贝壳；果壳'],
  'shine': ['ʃain', '照耀；发光'],
  'shiny': ['ʃaini', '光亮的；闪耀的'],
  'shirt': ['ʃə:t', '(男式)衬衫'],
  'shoe': ['ʃuː', '鞋子'],
  'shoe(s)': ['ʃu:', '鞋子（复数）'],
  'shop assistant': ['ə\'sistənt', '营业员'],
  'short': ['ʃɔ:t', '短的；矮的'],
  'short → shorter': ['ʃɔ:t', '更矮的'],
  'should': ['ʃud', '应该'],
  'shoulder': ['ʃəuldə', '肩'],
  'shout': ['ʃaut', '叫喊'],
  'show': ['ʃəu', '展示；演出'],
  'sick': ['sik', '有病的'],
  'sign': ['sain', '标志；符号'],
  'sing': ['siŋ', '唱；唱歌'],
  'sing and dance → sang and danced': ['siŋ', '唱歌和跳舞'],
  'singer': ['sindʒə', '歌唱家；歌手'],
  'sister': ['sistə', '姐妹'],
  'sit': ['sit', '坐'],
  'sit down': ['sɪt daʊn', '坐下'],
  'six': ['siks', '六'],
  'sixteen': ['siks\'ti:n', '十六'],
  'sixth': ['siksθ', '第六'],
  'sixty': ['siksti', '六十'],
  'size': ['saiz', '大小；尺寸；号码'],
  'skate': ['skeit', '滑冰'],
  'skateboard': ['skeitbɔ:d', '滑板'],
  'sketchbook': ['sketʃbuk', '写生簿；小品集'],
  'ski': ['ski', '滑雪,雪橇'],
  'skirt': ['skə:t', '裙子；边缘；外围'],
  'sky': ['skai', '天空；天气；顶峰'],
  'sleep': ['sli:p', '睡觉'],
  'small': ['smɔ:l', '小的'],
  'small → smaller': ['smɔ:l', '体型更小的'],
  'smell': ['smel', '嗅 闻'],
  'smoke': ['sməuk', '抽烟'],
  'snake': ['sneik', '蛇'],
  'snow': ['snəʊ', '雪'],
  'snowy': ['snəui', '下雪的'],
  'so': ['səu', '这样；这么；所以'],
  'sock': ['sɒk', '袜子'],
  'sock(s)': ['sɔk', '袜子（复数）'],
  'sofa': ['səufə', '沙发；长椅'],
  'soft': ['sɔft', '柔软'],
  'soil': ['sɔil', '土壤'],
  'soldier': ['səuldʒə', '士兵；兵蚁'],
  'some': ['sʌm', '一些'],
  'sometimes': ['sʌmtaimz', '有时候'],
  'son': ['sʌn', '儿子；女婿'],
  'sore': ['sɔ', '疼的'],
  'sorry': ['sɔri', '对不起；抱歉'],
  'spaceship': ['speisʃip', '宇宙飞船'],
  'speak': ['spi:k', '说'],
  'spell': ['spel', '拼；拼写'],
  'spoon': ['spu:n', '勺子'],
  'sports': ['spɔ:ts', '体育运动'],
  'spring': ['spriŋ', '春天'],
  'sprout': ['spraut', '苗；芽'],
  'square': ['skwεə', '广场'],
  'squirrel': ['skwə:rəl', '松鼠'],
  'stalk': ['stɔ:k', '主茎'],
  'stand': ['stænd', '站；站立'],
  'stand up': ['stænd ʌp', '起立'],
  'star': ['stɑ:', '星；星号；星状物'],
  'station': ['steiʃən', '车站；电台；基地'],
  'still': ['stil', '还；仍旧'],
  'stone': ['stəun', '石头'],
  'stop': ['stɔp', '停止'],
  'storm': ['stɔ:m', '暴风'],
  'straight': ['streit', '成直线地'],
  'stream': ['stri:m', '河；溪'],
  'string': ['striŋ', '绳子；线'],
  'strong': ['strɔŋ', '健壮的；坚固的'],
  'student': ['stju:dənt', '（大中学）学生'],
  'study': ['stʌdi', '学习；研究；学问'],
  'subject': ['sʌbdʒikt', '科目；主题'],
  'sugar': ['ʃugə', '糖'],
  'summer': ['sʌmə', '夏天'],
  'sun': ['sʌn', '太阳'],
  'sunday': ['sʌndi', '星期天'],
  'sunglasses': ['sʌnglɑ:siz', '太阳镜'],
  'sunny': ['sʌni', '晴朗的'],
  'supermarket': ['sju:pə,mɑ:kit', '超市'],
  'supper': ['sʌpə', '晚饭；晚餐会'],
  'sure': ['ʃuə', '当然；一定；可靠地'],
  'swan': ['swɔn', '天鹅 天鹅般纯洁的人'],
  'sweep': ['swi:p', '扫'],
  'sweet': ['swi:t', '甜的；悦耳的'],
  'swim': ['swim', '游泳'],
  'swing': ['swiŋ', '荡；荡秋千'],
  't-shirt': ['tiːʃɜːt', 'T恤衫'],
  'table': ['teibl', '桌子'],
  'tadpole': ['tædpəul', '蝌蚪'],
  'take': ['teik', '拿；乘'],
  'take pictures': ['teik', '照相'],
  'take pictures → took pictures': ['teik', '照相'],
  'talk': ['tɔ:k', '说话；谈论；演讲'],
  'tall': ['tɔ:l', '高的'],
  'tall → taller': ['tɔ:l', '更高的'],
  'tape': ['teip', '胶带；带子；磁带'],
  'taste': ['teist', '尝'],
  'tcow': ['kau', '母牛'],
  'tea': ['ti:', '茶'],
  'teacher': ['ti:tʃə', '教师'],
  'teach→teaches': ['ti:tʃ', '教'],
  'teeth': ['ti:θ', '牙(复数)'],
  'telephone': ['telifəun', '打电话'],
  'tell': ['tel', '告诉；吩咐'],
  'temple': ['templ', '庙宇；圣堂；寺院'],
  'ten': ['ten', '十'],
  'tenth': ['tenθ', '第十'],
  'term': ['tə:m', '学期；期限'],
  'text': ['tekst', '课文；文本'],
  'thank': ['θæŋk', '谢谢'],
  'thank you': ['θæŋk juː', '谢谢'],
  'theatre': ['θiətə', '剧场'],
  'their': ['ðεə', '他(她；它)们的'],
  'theirs': ['ðєəz', '他(她；它)们的'],
  'them': ['ðem', '他(她；它)们(宾格)'],
  'then': ['ðen', '那么；然后'],
  'there': ['ðεə', '那儿'],
  'these': ['ði:z', '这些'],
  'they': ['ðei', '他(她；它)们'],
  'thin': ['θin', '瘦的；细的；薄的'],
  'thin → thinner': ['θin', '更瘦的'],
  'thing': ['θiŋ', '东西；事情'],
  'think': ['θiŋk', '想；认为'],
  'third': ['θə:d', '第三'],
  'thirteen': ['θə:ti:n', '十三'],
  'thirtieth': ['θə:tiiθ', '第三十'],
  'thirty': ['θə:ti', '三十'],
  'thirty-three': ['θə:ti\'θri:', '三十三'],
  'this afternoon': [',ɑ:ftə:\'nu:n', '今天下午'],
  'this morning': ['ðis', '今天上午'],
  'three': ['θri:', '三'],
  'through': ['θru:', '穿过'],
  'throw': ['θrəu', '扔；转动（开关）'],
  'thunder': ['θʌndə', '雷；雷声'],
  'thursday': ['θə:zdi', '星期四'],
  'tiger': ['taiɡə', '老虎；凶残的人'],
  'time': ['taim', '时候；次；时代'],
  'timetable': ['taim,teibl', '课程表；火车时刻表'],
  'tired': ['taiəd', '疲劳的；累的'],
  'today': ['tə\'dei', '今天'],
  'toe': ['təu', '脚趾；足尖'],
  'too': ['tuː', 'two'],
  'tooth': ['tu:θ', '牙'],
  'top': ['tɔp', '顶部；头顶；山顶'],
  'tortoise': ['tɔ:təs', '乌龟'],
  'touch': ['tʌtʃ', '摸'],
  'tower': ['tauə', '塔；高楼'],
  'toy': ['tɔi', '玩具；玩物'],
  'traffic': ['træfik', '交通'],
  'traffic light': ['lait', '交通灯'],
  'train': ['treɪn', '火车'],
  'tram': ['træm', '（有轨）电车'],
  'tree': ['tri:', '树；家谱'],
  'triangle': ['traiæŋgl', '三角铁'],
  'trolley-bus': ['trɔlibʌs', '无轨电车'],
  'trousers': ['traʊzəz', '裤子；长裤'],
  'trunk': ['trʌŋk', '树干；大皮箱'],
  'try': ['trai', '试；试一下'],
  'tuesday': ['tju:zdi', '星期二'],
  'turn': ['tə:n', '转弯'],
  'tv reporter': ['ri\'pɔ:tə', '电视台记者'],
  'twelfth': ['twelfθ', '第十二'],
  'twelve': ['twelv', '十二'],
  'twentieth': ['twentiiθ', '第二十'],
  'twenty': ['twenti', '二十；二十年代'],
  'twenty-first': [',twenti\'fə:st', '第二十一'],
  'twenty-one': ['twenti,wʌn', '二十一'],
  'two': ['tu:', '二'],
  'type': ['taip', '类型；样式；榜样'],
  'ugly': ['ʌgli', '丑的'],
  'umbrella': ['ʌm\'brelə', '伞'],
  'uncle': ['ʌŋkl', '叔叔舅舅姨夫姑父'],
  'under': ['ʌndə', '在……下面'],
  'underground': ['ʌndəgraund', '地下'],
  'underground.': ['ʌndəgraund', '地铁'],
  'uniform': ['ju:nifɔ:m', '制服；军服'],
  'unit': ['ju:nit', '单元；单位'],
  'up': ['ʌp', '向上；上升；在……上面'],
  'use': ['ju:z', '使用'],
  'usually': ['ju:ʒuəli', '通常'],
  'vegetable': ['vedʒitəbl', '蔬菜；植物'],
  'very': ['veri', '很；非常'],
  'violin': [',vaiə\'lin', '小提琴 小提琴手'],
  'visit': ['vizit', '游览'],
  'visit grandparents': ['vizit', '看望祖父母'],
  'visit → visited': ['vizit', '看望'],
  'vocabulary': ['və\'kæbjuləri', '词汇；用词范围；词典'],
  'volleyball': ['vɔlibɔ:l', '排球'],
  'wait': ['weit', '等待'],
  'waiter': ['weitə', '服务员（男）'],
  'waitress': ['weitris', '女服务员'],
  'walk': ['wɔ:k', '走路；步行'],
  'wall': ['wɔ:l', '墙'],
  'want': ['wɔnt', '要；想见；追捕'],
  'warm': ['wɔ:m', '暖和的'],
  'wash': ['wɔʃ', '洗'],
  'wash → washed': ['wɔʃt', '洗'],
  'watch': ['wɔtʃ', '看；观看'],
  'watch insects': ['wɔtʃ', '观察昆虫'],
  'watch → watched': ['wɔtʃ', '看'],
  'watch→watches': ['wɔtʃ', '看'],
  'water': ['wɔ:tə', '水'],
  'watermelon': ['wɔ:tə,melən', '西瓜'],
  'wave': ['weiv', '浪；波浪'],
  'way': ['wei', '路；路程'],
  'we': ['wi:', '我们'],
  'wear': ['wεə', '穿戴'],
  'weather': ['weðə', '天气'],
  'wednesday': ['wenzdei', '星期三'],
  'week': ['wi:k', '周；星期'],
  'weekend': ['wi:kend', '周末'],
  'welcome': ['welkəm', '欢迎；受欢迎的'],
  'well': ['wel', '健康的'],
  'what': ['hwɔt', '什么；（感叹）多少'],
  'wheel': ['hwi:l', '轮子；车轮'],
  'when': ['(h)wen', '什么时候'],
  'where': ['(h)wєə', '在哪里；到哪里'],
  'which': ['hwitʃ', '哪一个'],
  'white': ['hwait', '白色的'],
  'who': ['huː', 'How'],
  'whose': ['hu:z', '谁的'],
  'why': ['hwai', '(表吃惊；满意等)哎呀！为什么？'],
  'will': ['wil', '将'],
  'win': ['win', '赢；获胜'],
  'wind': ['waind', '风'],
  'window': ['windəu', '窗'],
  'windy': ['windi', '有风的；风大的'],
  'wing': ['wiŋ', '翅膀'],
  'winter': ['wintə', '冬季；冬天'],
  'wolf': ['wulf', '狼'],
  'woman': ['wumən', '妇女'],
  'word': ['wə:d', '单词；言辞；歌词'],
  'work': ['wə:k', '工作'],
  'write': ['rait', '写'],
  'write a letter': ['rait', '写信'],
  'write a report': ['rait', '写报告'],
  'writer': ['raitə', '作家'],
  'year': ['jiə', '年；学年'],
  'yellow': ['jeləu', '黄色的'],
  'yes': ['jes', '是的'],
  'yet': ['jet', '还(没有)…还(不)…'],
  'you': ['ju:', '你'],
  'young': ['jʌŋ', '年轻的'],
  'young → younger': ['jʌŋ', '更年轻的'],
  'yours': ['juəz', '你的；你们的'],
  'zebra': ['zi:brə', '斑马；有斑纹的'],
  'zoo': ['zu:', '动物园'],
  'zoo keeper': ['ki:pə', '饲养员'],
}
